// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: analyzer.proto

package analyzer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ComparisonType distinguishes baseline from comparison window traces.
// Only used by the /compare endpoint; ignored by /stream.
type ComparisonType int32

const (
	ComparisonType_COMPARISON_TYPE_UNSPECIFIED ComparisonType = 0
	ComparisonType_BASELINE                    ComparisonType = 1
	ComparisonType_COMPARISON                  ComparisonType = 2
)

// Enum value maps for ComparisonType.
var (
	ComparisonType_name = map[int32]string{
		0: "COMPARISON_TYPE_UNSPECIFIED",
		1: "BASELINE",
		2: "COMPARISON",
	}
	ComparisonType_value = map[string]int32{
		"COMPARISON_TYPE_UNSPECIFIED": 0,
		"BASELINE":                    1,
		"COMPARISON":                  2,
	}
)

func (x ComparisonType) Enum() *ComparisonType {
	p := new(ComparisonType)
	*p = x
	return p
}

func (x ComparisonType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComparisonType) Descriptor() protoreflect.EnumDescriptor {
	return file_analyzer_proto_enumTypes[0].Descriptor()
}

func (ComparisonType) Type() protoreflect.EnumType {
	return &file_analyzer_proto_enumTypes[0]
}

func (x ComparisonType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComparisonType.Descriptor instead.
func (ComparisonType) EnumDescriptor() ([]byte, []int) {
	return file_analyzer_proto_rawDescGZIP(), []int{0}
}

// CallPath represents one step in a call chain.
type CallPath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	OperationName string                 `protobuf:"bytes,2,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	Exemplars     []*Exemplar            `protobuf:"bytes,5,rep,name=exemplars,proto3" json:"exemplars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallPath) Reset() {
	*x = CallPath{}
	mi := &file_analyzer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallPath) ProtoMessage() {}

func (x *CallPath) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallPath.ProtoReflect.Descriptor instead.
func (*CallPath) Descriptor() ([]byte, []int) {
	return file_analyzer_proto_rawDescGZIP(), []int{0}
}

func (x *CallPath) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *CallPath) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *CallPath) GetExemplars() []*Exemplar {
	if x != nil {
		return x.Exemplars
	}
	return nil
}

// Exemplar holds a trace+span reference pointing to a concrete example for a call path.
type Exemplar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId        string                 `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exemplar) Reset() {
	*x = Exemplar{}
	mi := &file_analyzer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exemplar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exemplar) ProtoMessage() {}

func (x *Exemplar) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exemplar.ProtoReflect.Descriptor instead.
func (*Exemplar) Descriptor() ([]byte, []int) {
	return file_analyzer_proto_rawDescGZIP(), []int{1}
}

func (x *Exemplar) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Exemplar) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

// PathStats holds aggregated duration and frequency for one call chain window.
type PathStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duration      *durationpb.Duration   `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"`
	Frequency     int32                  `protobuf:"varint,2,opt,name=frequency,proto3" json:"frequency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathStats) Reset() {
	*x = PathStats{}
	mi := &file_analyzer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathStats) ProtoMessage() {}

func (x *PathStats) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathStats.ProtoReflect.Descriptor instead.
func (*PathStats) Descriptor() ([]byte, []int) {
	return file_analyzer_proto_rawDescGZIP(), []int{2}
}

func (x *PathStats) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *PathStats) GetFrequency() int32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

// CallChainSummary represents one call chain with its aggregated stats.
// diff is populated only in compare responses (report_window_diff).
type CallChainSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallPath      []*CallPath            `protobuf:"bytes,1,rep,name=call_path,json=callPath,proto3" json:"call_path,omitempty"`
	Base          *PathStats             `protobuf:"bytes,4,opt,name=base,proto3" json:"base,omitempty"`
	Diff          *PathStats             `protobuf:"bytes,5,opt,name=diff,proto3" json:"diff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallChainSummary) Reset() {
	*x = CallChainSummary{}
	mi := &file_analyzer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallChainSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallChainSummary) ProtoMessage() {}

func (x *CallChainSummary) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallChainSummary.ProtoReflect.Descriptor instead.
func (*CallChainSummary) Descriptor() ([]byte, []int) {
	return file_analyzer_proto_rawDescGZIP(), []int{3}
}

func (x *CallChainSummary) GetCallPath() []*CallPath {
	if x != nil {
		return x.CallPath
	}
	return nil
}

func (x *CallChainSummary) GetBase() *PathStats {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *CallChainSummary) GetDiff() *PathStats {
	if x != nil {
		return x.Diff
	}
	return nil
}

// AnalyzeResponse returns call chain summaries for one or two analysis windows.
// report_window_2 and report_window_diff are only populated by the compare endpoint.
type AnalyzeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ReportWindow_1   []*CallChainSummary    `protobuf:"bytes,1,rep,name=report_window_1,json=reportWindow1,proto3" json:"report_window_1,omitempty"`
	ReportWindow_2   []*CallChainSummary    `protobuf:"bytes,2,rep,name=report_window_2,json=reportWindow2,proto3" json:"report_window_2,omitempty"`
	ReportWindowDiff []*CallChainSummary    `protobuf:"bytes,3,rep,name=report_window_diff,json=reportWindowDiff,proto3" json:"report_window_diff,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_analyzer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_analyzer_proto_rawDescGZIP(), []int{4}
}

func (x *AnalyzeResponse) GetReportWindow_1() []*CallChainSummary {
	if x != nil {
		return x.ReportWindow_1
	}
	return nil
}

func (x *AnalyzeResponse) GetReportWindow_2() []*CallChainSummary {
	if x != nil {
		return x.ReportWindow_2
	}
	return nil
}

func (x *AnalyzeResponse) GetReportWindowDiff() []*CallChainSummary {
	if x != nil {
		return x.ReportWindowDiff
	}
	return nil
}

// StreamMetadata is sent once at the start of the stream and identifies the
// service and operation being analysed.
type StreamMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	OperationName string                 `protobuf:"bytes,2,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMetadata) Reset() {
	*x = StreamMetadata{}
	mi := &file_analyzer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMetadata) ProtoMessage() {}

func (x *StreamMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMetadata.ProtoReflect.Descriptor instead.
func (*StreamMetadata) Descriptor() ([]byte, []int) {
	return file_analyzer_proto_rawDescGZIP(), []int{5}
}

func (x *StreamMetadata) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *StreamMetadata) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

// AnalysisData carries one Jaeger trace in the standard HTTP API JSON format
// (the same JSON a call to GET /api/traces/{id} returns).
type AnalysisData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw bytes of a single Jaeger HTTP API trace JSON
	// ({"data":[{"traceID":…,"spans":[…],"processes":{…}}]}).
	TraceJson     []byte         `protobuf:"bytes,1,opt,name=trace_json,json=traceJson,proto3" json:"trace_json,omitempty"`
	Type          ComparisonType `protobuf:"varint,2,opt,name=type,proto3,enum=crisp.analyzer.ComparisonType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisData) Reset() {
	*x = AnalysisData{}
	mi := &file_analyzer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisData) ProtoMessage() {}

func (x *AnalysisData) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisData.ProtoReflect.Descriptor instead.
func (*AnalysisData) Descriptor() ([]byte, []int) {
	return file_analyzer_proto_rawDescGZIP(), []int{6}
}

func (x *AnalysisData) GetTraceJson() []byte {
	if x != nil {
		return x.TraceJson
	}
	return nil
}

func (x *AnalysisData) GetType() ComparisonType {
	if x != nil {
		return x.Type
	}
	return ComparisonType_COMPARISON_TYPE_UNSPECIFIED
}

// AnalyzeRequest is the per-message envelope sent by the client.
type AnalyzeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*AnalyzeRequest_Metadata
	//	*AnalyzeRequest_Traces
	Data          isAnalyzeRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_analyzer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_analyzer_proto_rawDescGZIP(), []int{7}
}

func (x *AnalyzeRequest) GetData() isAnalyzeRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AnalyzeRequest) GetMetadata() *StreamMetadata {
	if x != nil {
		if x, ok := x.Data.(*AnalyzeRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *AnalyzeRequest) GetTraces() *AnalysisData {
	if x != nil {
		if x, ok := x.Data.(*AnalyzeRequest_Traces); ok {
			return x.Traces
		}
	}
	return nil
}

type isAnalyzeRequest_Data interface {
	isAnalyzeRequest_Data()
}

type AnalyzeRequest_Metadata struct {
	Metadata *StreamMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type AnalyzeRequest_Traces struct {
	Traces *AnalysisData `protobuf:"bytes,2,opt,name=traces,proto3,oneof"`
}

func (*AnalyzeRequest_Metadata) isAnalyzeRequest_Data() {}

func (*AnalyzeRequest_Traces) isAnalyzeRequest_Data() {}

var File_analyzer_proto protoreflect.FileDescriptor

const file_analyzer_proto_rawDesc = "" +
	"\n" +
	"\x0eanalyzer.proto\x12\x0ecrisp.analyzer\x1a\x1egoogle/protobuf/duration.proto\"\x83\x01\n" +
	"\bCallPath\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12%\n" +
	"\x0eoperation_name\x18\x02 \x01(\tR\roperationName\x126\n" +
	"\texemplars\x18\x05 \x03(\v2\x18.crisp.analyzer.ExemplarR\texemplars\">\n" +
	"\bExemplar\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\tR\x06spanId\"`\n" +
	"\tPathStats\x125\n" +
	"\bduration\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12\x1c\n" +
	"\tfrequency\x18\x02 \x01(\x05R\tfrequency\"\xa7\x01\n" +
	"\x10CallChainSummary\x125\n" +
	"\tcall_path\x18\x01 \x03(\v2\x18.crisp.analyzer.CallPathR\bcallPath\x12-\n" +
	"\x04base\x18\x04 \x01(\v2\x19.crisp.analyzer.PathStatsR\x04base\x12-\n" +
	"\x04diff\x18\x05 \x01(\v2\x19.crisp.analyzer.PathStatsR\x04diff\"\xf5\x01\n" +
	"\x0fAnalyzeResponse\x12H\n" +
	"\x0freport_window_1\x18\x01 \x03(\v2 .crisp.analyzer.CallChainSummaryR\rreportWindow1\x12H\n" +
	"\x0freport_window_2\x18\x02 \x03(\v2 .crisp.analyzer.CallChainSummaryR\rreportWindow2\x12N\n" +
	"\x12report_window_diff\x18\x03 \x03(\v2 .crisp.analyzer.CallChainSummaryR\x10reportWindowDiff\"Z\n" +
	"\x0eStreamMetadata\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12%\n" +
	"\x0eoperation_name\x18\x02 \x01(\tR\roperationName\"a\n" +
	"\fAnalysisData\x12\x1d\n" +
	"\n" +
	"trace_json\x18\x01 \x01(\fR\ttraceJson\x122\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1e.crisp.analyzer.ComparisonTypeR\x04type\"\x8e\x01\n" +
	"\x0eAnalyzeRequest\x12<\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1e.crisp.analyzer.StreamMetadataH\x00R\bmetadata\x126\n" +
	"\x06traces\x18\x02 \x01(\v2\x1c.crisp.analyzer.AnalysisDataH\x00R\x06tracesB\x06\n" +
	"\x04data*O\n" +
	"\x0eComparisonType\x12\x1f\n" +
	"\x1bCOMPARISON_TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bBASELINE\x10\x01\x12\x0e\n" +
	"\n" +
	"COMPARISON\x10\x02B]\n" +
	"\x12com.crisp.analyzerB\rAnalyzerProtoP\x01Z6github.com/uber-research/CRISP/go/crisp/proto/analyzerb\x06proto3"

var (
	file_analyzer_proto_rawDescOnce sync.Once
	file_analyzer_proto_rawDescData []byte
)

func file_analyzer_proto_rawDescGZIP() []byte {
	file_analyzer_proto_rawDescOnce.Do(func() {
		file_analyzer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analyzer_proto_rawDesc), len(file_analyzer_proto_rawDesc)))
	})
	return file_analyzer_proto_rawDescData
}

var file_analyzer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_analyzer_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_analyzer_proto_goTypes = []any{
	(ComparisonType)(0),         // 0: crisp.analyzer.ComparisonType
	(*CallPath)(nil),            // 1: crisp.analyzer.CallPath
	(*Exemplar)(nil),            // 2: crisp.analyzer.Exemplar
	(*PathStats)(nil),           // 3: crisp.analyzer.PathStats
	(*CallChainSummary)(nil),    // 4: crisp.analyzer.CallChainSummary
	(*AnalyzeResponse)(nil),     // 5: crisp.analyzer.AnalyzeResponse
	(*StreamMetadata)(nil),      // 6: crisp.analyzer.StreamMetadata
	(*AnalysisData)(nil),        // 7: crisp.analyzer.AnalysisData
	(*AnalyzeRequest)(nil),      // 8: crisp.analyzer.AnalyzeRequest
	(*durationpb.Duration)(nil), // 9: google.protobuf.Duration
}
var file_analyzer_proto_depIdxs = []int32{
	2,  // 0: crisp.analyzer.CallPath.exemplars:type_name -> crisp.analyzer.Exemplar
	9,  // 1: crisp.analyzer.PathStats.duration:type_name -> google.protobuf.Duration
	1,  // 2: crisp.analyzer.CallChainSummary.call_path:type_name -> crisp.analyzer.CallPath
	3,  // 3: crisp.analyzer.CallChainSummary.base:type_name -> crisp.analyzer.PathStats
	3,  // 4: crisp.analyzer.CallChainSummary.diff:type_name -> crisp.analyzer.PathStats
	4,  // 5: crisp.analyzer.AnalyzeResponse.report_window_1:type_name -> crisp.analyzer.CallChainSummary
	4,  // 6: crisp.analyzer.AnalyzeResponse.report_window_2:type_name -> crisp.analyzer.CallChainSummary
	4,  // 7: crisp.analyzer.AnalyzeResponse.report_window_diff:type_name -> crisp.analyzer.CallChainSummary
	0,  // 8: crisp.analyzer.AnalysisData.type:type_name -> crisp.analyzer.ComparisonType
	6,  // 9: crisp.analyzer.AnalyzeRequest.metadata:type_name -> crisp.analyzer.StreamMetadata
	7,  // 10: crisp.analyzer.AnalyzeRequest.traces:type_name -> crisp.analyzer.AnalysisData
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_analyzer_proto_init() }
func file_analyzer_proto_init() {
	if File_analyzer_proto != nil {
		return
	}
	file_analyzer_proto_msgTypes[7].OneofWrappers = []any{
		(*AnalyzeRequest_Metadata)(nil),
		(*AnalyzeRequest_Traces)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analyzer_proto_rawDesc), len(file_analyzer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_analyzer_proto_goTypes,
		DependencyIndexes: file_analyzer_proto_depIdxs,
		EnumInfos:         file_analyzer_proto_enumTypes,
		MessageInfos:      file_analyzer_proto_msgTypes,
	}.Build()
	File_analyzer_proto = out.File
	file_analyzer_proto_goTypes = nil
	file_analyzer_proto_depIdxs = nil
}
