load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_binary(
    name = "cpsegments",
    embed = [":cpsegments_lib"],
    importpath = "github.com/uber-research/CRISP/go/tools/cpsegments",
    visibility = ["//visibility:public"],
)

go_library(
    name = "cpsegments_lib",
    srcs = ["main.go"],
    importpath = "github.com/uber-research/CRISP/go/tools/cpsegments",
    visibility = ["//visibility:private"],
    deps = [
        "//go/crisp",
        "//go/crisp/jaeger",
    ],
)
